# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/daemon/config/protocol.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protobuf/daemon/config/protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%protobuf/daemon/config/protocol.proto\x12\x06\x63onfig*A\n\x08Protocol\x12\x14\n\x10UNKNOWN_PROTOCOL\x10\x00\x12\x07\n\x03UDP\x10\x01\x12\x07\n\x03TCP\x10\x02\x12\r\n\tWebtunnel\x10\x03\x42.Z,github.com/NordSecurity/nordvpn-linux/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.daemon.config.protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/NordSecurity/nordvpn-linux/config'
  _globals['_PROTOCOL']._serialized_start=49
  _globals['_PROTOCOL']._serialized_end=114
# @@protoc_insertion_point(module_scope)
