version: "2"
run:
  timeout: 2m
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - exhaustive
    - goconst
    - goprintffuncname
    - govet
    - misspell
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - depguard
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third-party
    rules:
      - linters: 
        - staticcheck
        text: "ST1005:" # systematically, disable all the linter issues on errors strings capitalization, or ending with a punctuation mark
  settings:
    depguard:
      rules:
        no-std-log:
          list-mode: lax
          files:
            - $all
            - "!**/nordvpn-linux/log/*.go"
          deny:
            - pkg: "log"
              desc: "Use internal logger (github.com/NordSecurity/nordvpn-linux/log) instead"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third-party
