// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: norduser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartFileshareStatus int32

const (
	StartFileshareStatus_SUCCESS                        StartFileshareStatus = 0
	StartFileshareStatus_ALREADY_RUNNING                StartFileshareStatus = 1
	StartFileshareStatus_ALREADY_RUNNING_FOR_OTHER_USER StartFileshareStatus = 2
	StartFileshareStatus_FAILED_TO_CREATE_UNIX_SOCKET   StartFileshareStatus = 3
	StartFileshareStatus_MESHNET_NOT_ENABLED            StartFileshareStatus = 4
	StartFileshareStatus_ADDRESS_ALREADY_IN_USE         StartFileshareStatus = 5
	StartFileshareStatus_FAILED_TO_ENABLE               StartFileshareStatus = 6
)

// Enum value maps for StartFileshareStatus.
var (
	StartFileshareStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "ALREADY_RUNNING",
		2: "ALREADY_RUNNING_FOR_OTHER_USER",
		3: "FAILED_TO_CREATE_UNIX_SOCKET",
		4: "MESHNET_NOT_ENABLED",
		5: "ADDRESS_ALREADY_IN_USE",
		6: "FAILED_TO_ENABLE",
	}
	StartFileshareStatus_value = map[string]int32{
		"SUCCESS":                        0,
		"ALREADY_RUNNING":                1,
		"ALREADY_RUNNING_FOR_OTHER_USER": 2,
		"FAILED_TO_CREATE_UNIX_SOCKET":   3,
		"MESHNET_NOT_ENABLED":            4,
		"ADDRESS_ALREADY_IN_USE":         5,
		"FAILED_TO_ENABLE":               6,
	}
)

func (x StartFileshareStatus) Enum() *StartFileshareStatus {
	p := new(StartFileshareStatus)
	*p = x
	return p
}

func (x StartFileshareStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartFileshareStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_norduser_proto_enumTypes[0].Descriptor()
}

func (StartFileshareStatus) Type() protoreflect.EnumType {
	return &file_norduser_proto_enumTypes[0]
}

func (x StartFileshareStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartFileshareStatus.Descriptor instead.
func (StartFileshareStatus) EnumDescriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_norduser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_norduser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{0}
}

type StartFileshareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartFileshareStatus StartFileshareStatus `protobuf:"varint,1,opt,name=start_fileshare_status,json=startFileshareStatus,proto3,enum=norduserpb.StartFileshareStatus" json:"start_fileshare_status,omitempty"`
}

func (x *StartFileshareResponse) Reset() {
	*x = StartFileshareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_norduser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartFileshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFileshareResponse) ProtoMessage() {}

func (x *StartFileshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_norduser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFileshareResponse.ProtoReflect.Descriptor instead.
func (*StartFileshareResponse) Descriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{1}
}

func (x *StartFileshareResponse) GetStartFileshareStatus() StartFileshareStatus {
	if x != nil {
		return x.StartFileshareStatus
	}
	return StartFileshareStatus_SUCCESS
}

type StopFileshareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StopFileshareResponse) Reset() {
	*x = StopFileshareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_norduser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopFileshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFileshareResponse) ProtoMessage() {}

func (x *StopFileshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_norduser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFileshareResponse.ProtoReflect.Descriptor instead.
func (*StopFileshareResponse) Descriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{2}
}

func (x *StopFileshareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_norduser_proto protoreflect.FileDescriptor

var file_norduser_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x70, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x16, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x20, 0x2e, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x14, 0x73, 0x74, 0x61, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x70, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0xc9, 0x01, 0x0a, 0x14, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x52, 0x55, 0x4e, 0x4e,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x4f, 0x54, 0x48,
	0x45, 0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x49, 0x58, 0x5f, 0x53, 0x4f, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4d,
	0x45, 0x53, 0x48, 0x4e, 0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x4e, 0x41, 0x42, 0x4c,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x5f,
	0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x49, 0x4e, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x05,
	0x12, 0x14, 0x0a, 0x10, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x45, 0x4e,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x06, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76, 0x70, 0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f,
	0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_norduser_proto_rawDescOnce sync.Once
	file_norduser_proto_rawDescData = file_norduser_proto_rawDesc
)

func file_norduser_proto_rawDescGZIP() []byte {
	file_norduser_proto_rawDescOnce.Do(func() {
		file_norduser_proto_rawDescData = protoimpl.X.CompressGZIP(file_norduser_proto_rawDescData)
	})
	return file_norduser_proto_rawDescData
}

var file_norduser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_norduser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_norduser_proto_goTypes = []interface{}{
	(StartFileshareStatus)(0),      // 0: norduserpb.StartFileshareStatus
	(*Empty)(nil),                  // 1: norduserpb.Empty
	(*StartFileshareResponse)(nil), // 2: norduserpb.StartFileshareResponse
	(*StopFileshareResponse)(nil),  // 3: norduserpb.StopFileshareResponse
}
var file_norduser_proto_depIdxs = []int32{
	0, // 0: norduserpb.StartFileshareResponse.start_fileshare_status:type_name -> norduserpb.StartFileshareStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_norduser_proto_init() }
func file_norduser_proto_init() {
	if File_norduser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_norduser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_norduser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartFileshareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_norduser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopFileshareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_norduser_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_norduser_proto_goTypes,
		DependencyIndexes: file_norduser_proto_depIdxs,
		EnumInfos:         file_norduser_proto_enumTypes,
		MessageInfos:      file_norduser_proto_msgTypes,
	}.Build()
	File_norduser_proto = out.File
	file_norduser_proto_rawDesc = nil
	file_norduser_proto_goTypes = nil
	file_norduser_proto_depIdxs = nil
}
