// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: norduser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_norduser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_norduser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{0}
}

type StopNorduserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable bool `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Restart bool `protobuf:"varint,2,opt,name=restart,proto3" json:"restart,omitempty"`
}

func (x *StopNorduserRequest) Reset() {
	*x = StopNorduserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_norduser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopNorduserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNorduserRequest) ProtoMessage() {}

func (x *StopNorduserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_norduser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNorduserRequest.ProtoReflect.Descriptor instead.
func (*StopNorduserRequest) Descriptor() ([]byte, []int) {
	return file_norduser_proto_rawDescGZIP(), []int{1}
}

func (x *StopNorduserRequest) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

func (x *StopNorduserRequest) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

var File_norduser_proto protoreflect.FileDescriptor

var file_norduser_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x49, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x72,
	0x64, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e,
	0x6f, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64,
	0x76, 0x70, 0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_norduser_proto_rawDescOnce sync.Once
	file_norduser_proto_rawDescData = file_norduser_proto_rawDesc
)

func file_norduser_proto_rawDescGZIP() []byte {
	file_norduser_proto_rawDescOnce.Do(func() {
		file_norduser_proto_rawDescData = protoimpl.X.CompressGZIP(file_norduser_proto_rawDescData)
	})
	return file_norduser_proto_rawDescData
}

var file_norduser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_norduser_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: norduserpb.Empty
	(*StopNorduserRequest)(nil), // 1: norduserpb.StopNorduserRequest
}
var file_norduser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_norduser_proto_init() }
func file_norduser_proto_init() {
	if File_norduser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_norduser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_norduser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopNorduserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_norduser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_norduser_proto_goTypes,
		DependencyIndexes: file_norduser_proto_depIdxs,
		MessageInfos:      file_norduser_proto_msgTypes,
	}.Build()
	File_norduser_proto = out.File
	file_norduser_proto_rawDesc = nil
	file_norduser_proto_goTypes = nil
	file_norduser_proto_depIdxs = nil
}
