// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.6
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Norduser_Ping_FullMethodName           = "/norduserpb.Norduser/Ping"
	Norduser_StartFileshare_FullMethodName = "/norduserpb.Norduser/StartFileshare"
	Norduser_StopFileshare_FullMethodName  = "/norduserpb.Norduser/StopFileshare"
	Norduser_Stop_FullMethodName           = "/norduserpb.Norduser/Stop"
)

// NorduserClient is the client API for Norduser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NorduserClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// StartsFileshare starts fileshare process
	StartFileshare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// StopFileshare stops fileshare process
	StopFileshare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Stop stops norduser process
	Stop(ctx context.Context, in *StopNorduserRequest, opts ...grpc.CallOption) (*Empty, error)
}

type norduserClient struct {
	cc grpc.ClientConnInterface
}

func NewNorduserClient(cc grpc.ClientConnInterface) NorduserClient {
	return &norduserClient{cc}
}

func (c *norduserClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Norduser_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *norduserClient) StartFileshare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Norduser_StartFileshare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *norduserClient) StopFileshare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Norduser_StopFileshare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *norduserClient) Stop(ctx context.Context, in *StopNorduserRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Norduser_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NorduserServer is the server API for Norduser service.
// All implementations must embed UnimplementedNorduserServer
// for forward compatibility.
type NorduserServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	// StartsFileshare starts fileshare process
	StartFileshare(context.Context, *Empty) (*Empty, error)
	// StopFileshare stops fileshare process
	StopFileshare(context.Context, *Empty) (*Empty, error)
	// Stop stops norduser process
	Stop(context.Context, *StopNorduserRequest) (*Empty, error)
	mustEmbedUnimplementedNorduserServer()
}

// UnimplementedNorduserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNorduserServer struct{}

func (UnimplementedNorduserServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNorduserServer) StartFileshare(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFileshare not implemented")
}
func (UnimplementedNorduserServer) StopFileshare(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopFileshare not implemented")
}
func (UnimplementedNorduserServer) Stop(context.Context, *StopNorduserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedNorduserServer) mustEmbedUnimplementedNorduserServer() {}
func (UnimplementedNorduserServer) testEmbeddedByValue()                  {}

// UnsafeNorduserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NorduserServer will
// result in compilation errors.
type UnsafeNorduserServer interface {
	mustEmbedUnimplementedNorduserServer()
}

func RegisterNorduserServer(s grpc.ServiceRegistrar, srv NorduserServer) {
	// If the following call pancis, it indicates UnimplementedNorduserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Norduser_ServiceDesc, srv)
}

func _Norduser_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorduserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Norduser_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorduserServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Norduser_StartFileshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorduserServer).StartFileshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Norduser_StartFileshare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorduserServer).StartFileshare(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Norduser_StopFileshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorduserServer).StopFileshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Norduser_StopFileshare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorduserServer).StopFileshare(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Norduser_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopNorduserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorduserServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Norduser_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorduserServer).Stop(ctx, req.(*StopNorduserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Norduser_ServiceDesc is the grpc.ServiceDesc for Norduser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Norduser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norduserpb.Norduser",
	HandlerType: (*NorduserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Norduser_Ping_Handler,
		},
		{
			MethodName: "StartFileshare",
			Handler:    _Norduser_StartFileshare_Handler,
		},
		{
			MethodName: "StopFileshare",
			Handler:    _Norduser_StopFileshare_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Norduser_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
