Vagrant.configure("2") do |config|
  # sync project folder in /vagrant folder
  config.vm.synced_folder ENV["WORKDIR"], "/vagrant"

  # libvirt uses rsync and there are issues with the snap folders
  # Because of this for libvirt override sync to exclude problematic folders
  config.vm.provider "libvirt" do |lv, override|
    override.vm.synced_folder ENV["WORKDIR"], "/vagrant",
      type: "rsync",
      rsync__auto: true,
      rsync__args: ["--archive", "--delete", "--compress"],
      rsync__exclude: ["parts", "prime", ".git"]
  end

  config.vm.network "private_network", type: "dhcp"

  # install dependencies
  config.vm.provision "shell", path: "provision_snap.sh"

  config.vm.define "ubuntu2204", autostart: false do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2204"
  end

  config.vm.define "default", primary: true  do |default|
    default.vm.box = "generic/ubuntu2204"
  end
end
