Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
  end

  config.vm.network "private_network", type: "dhcp"
  # mount the project folder. WORKDIR must be set
  config.vm.synced_folder ENV["WORKDIR"], "/vagrant"

  # install dependencies
  config.vm.provision "shell", path: "provision_snap.sh"

  config.vm.define "ubuntu2204", autostart: false do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2204"
  end

  config.vm.define "default", primary: true  do |default|
    default.vm.box = "generic/ubuntu2204"
  end
end
