# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/daemon/login.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protobuf/daemon/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotobuf/daemon/login.proto\x12\x02pb\"1\n\x12LoginOAuth2Request\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.pb.LoginType\"H\n\x1aLoginOAuth2CallbackRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.pb.LoginType\"*\n\rLoginResponse\x12\x0c\n\x04type\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x05 \x01(\t\"I\n\x13LoginOAuth2Response\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.pb.LoginOAuth2Status\x12\x0b\n\x03url\x18\x02 \x01(\t*M\n\tLoginType\x12\x15\n\x11LoginType_UNKNOWN\x10\x00\x12\x13\n\x0fLoginType_LOGIN\x10\x01\x12\x14\n\x10LoginType_SIGNUP\x10\x02*]\n\x11LoginOAuth2Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x18\n\x14UNKNOWN_OAUTH2_ERROR\x10\x01\x12\x15\n\x11\x41LREADY_LOGGED_IN\x10\x02\x12\n\n\x06NO_NET\x10\x03\x42\x31Z/github.com/NordSecurity/nordvpn-linux/daemon/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.daemon.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/NordSecurity/nordvpn-linux/daemon/pb'
  _globals['_LOGINTYPE']._serialized_start=279
  _globals['_LOGINTYPE']._serialized_end=356
  _globals['_LOGINOAUTH2STATUS']._serialized_start=358
  _globals['_LOGINOAUTH2STATUS']._serialized_end=451
  _globals['_LOGINOAUTH2REQUEST']._serialized_start=35
  _globals['_LOGINOAUTH2REQUEST']._serialized_end=84
  _globals['_LOGINOAUTH2CALLBACKREQUEST']._serialized_start=86
  _globals['_LOGINOAUTH2CALLBACKREQUEST']._serialized_end=158
  _globals['_LOGINRESPONSE']._serialized_start=160
  _globals['_LOGINRESPONSE']._serialized_end=202
  _globals['_LOGINOAUTH2RESPONSE']._serialized_start=204
  _globals['_LOGINOAUTH2RESPONSE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
