# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_selection_rule.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server_selection_rule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bserver_selection_rule.proto\x12\x02pb*\x9f\x01\n\x13ServerSelectionRule\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bRECOMMENDED\x10\x01\x12\x08\n\x04\x43ITY\x10\x02\x12\x0b\n\x07\x43OUNTRY\x10\x03\x12\x13\n\x0fSPECIFIC_SERVER\x10\x04\x12\t\n\x05GROUP\x10\x05\x12\x16\n\x12\x43OUNTRY_WITH_GROUP\x10\x06\x12\x1e\n\x1aSPECIFIC_SERVER_WITH_GROUP\x10\x07\x42.Z,github.com/NordSecurity/nordvpn-linux/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_selection_rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/NordSecurity/nordvpn-linux/config'
  _globals['_SERVERSELECTIONRULE']._serialized_start=36
  _globals['_SERVERSELECTIONRULE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
