# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_response.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16service_response.proto\x12\x06meshpb\x1a\x0b\x65mpty.proto\"\xa3\x01\n\x0fMeshnetResponse\x12\x1e\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\r.meshpb.EmptyH\x00\x12\x31\n\rservice_error\x18\x02 \x01(\x0e\x32\x18.meshpb.ServiceErrorCodeH\x00\x12\x31\n\rmeshnet_error\x18\x03 \x01(\x0e\x32\x18.meshpb.MeshnetErrorCodeH\x00\x42\n\n\x08response\"m\n\x0fServiceResponse\x12\x1e\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\r.meshpb.EmptyH\x00\x12.\n\nerror_code\x18\x02 \x01(\x0e\x32\x18.meshpb.ServiceErrorCodeH\x00\x42\n\n\x08response\"b\n\x13ServiceBoolResponse\x12\x0f\n\x05value\x18\x01 \x01(\x08H\x00\x12.\n\nerror_code\x18\x02 \x01(\x0e\x32\x18.meshpb.ServiceErrorCodeH\x00\x42\n\n\x08response\"+\n\rEnabledStatus\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x0b\n\x03uid\x18\x02 \x01(\r\"x\n\x11IsEnabledResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x15.meshpb.EnabledStatusH\x00\x12.\n\nerror_code\x18\x02 \x01(\x0e\x32\x18.meshpb.ServiceErrorCodeH\x00\x42\n\n\x08response*J\n\x10ServiceErrorCode\x12\x11\n\rNOT_LOGGED_IN\x10\x00\x12\x0f\n\x0b\x41PI_FAILURE\x10\x01\x12\x12\n\x0e\x43ONFIG_FAILURE\x10\x02*\xcb\x01\n\x10MeshnetErrorCode\x12\x12\n\x0eNOT_REGISTERED\x10\x00\x12\x0f\n\x0bLIB_FAILURE\x10\x01\x12\x13\n\x0f\x41LREADY_ENABLED\x10\x03\x12\x14\n\x10\x41LREADY_DISABLED\x10\x04\x12\x0f\n\x0bNOT_ENABLED\x10\x05\x12\x10\n\x0cTECH_FAILURE\x10\x06\x12\x11\n\rTUNNEL_CLOSED\x10\x07\x12\x14\n\x10\x43ONFLICT_WITH_PQ\x10\x08\x12\x1b\n\x17\x43ONFLICT_WITH_PQ_SERVER\x10\tB2Z0github.com/NordSecurity/nordvpn-linux/meshnet/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/NordSecurity/nordvpn-linux/meshnet/pb'
  _globals['_SERVICEERRORCODE']._serialized_start=591
  _globals['_SERVICEERRORCODE']._serialized_end=665
  _globals['_MESHNETERRORCODE']._serialized_start=668
  _globals['_MESHNETERRORCODE']._serialized_end=871
  _globals['_MESHNETRESPONSE']._serialized_start=48
  _globals['_MESHNETRESPONSE']._serialized_end=211
  _globals['_SERVICERESPONSE']._serialized_start=213
  _globals['_SERVICERESPONSE']._serialized_end=322
  _globals['_SERVICEBOOLRESPONSE']._serialized_start=324
  _globals['_SERVICEBOOLRESPONSE']._serialized_end=422
  _globals['_ENABLEDSTATUS']._serialized_start=424
  _globals['_ENABLEDSTATUS']._serialized_end=467
  _globals['_ISENABLEDRESPONSE']._serialized_start=469
  _globals['_ISENABLEDRESPONSE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
