# build.yml defines jobs for building binary artifacts.
include: /ci/jobs/.cond.yml
build/binaries:
  stage: build
  image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
  script: $CI_PROJECT_DIR/ci/compile.sh
  dependencies: []
  artifacts:
    paths:
      - $CI_PROJECT_DIR/bin
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
build/binaries-candidate:
  stage: build
  image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
  rules:
    - !reference [.cond/on-click, rules]
  variables:
    ENVIRONMENT: prod
  script: $CI_PROJECT_DIR/ci/compile.sh
  dependencies: []
  artifacts:
    paths:
      - $CI_PROJECT_DIR/bin
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
build/openvpn:
  stage: build
  image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
    - !reference [.cond/on-click, rules]
  script: $CI_PROJECT_DIR/build/openvpn/build.sh
  dependencies: []
  artifacts:
    paths:
      - $CI_PROJECT_DIR/bin
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
build/data:
  stage: build
  image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
    - !reference [.cond/on-click, rules]
  script: $CI_PROJECT_DIR/ci/data.sh
  dependencies: []
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*
build/licenses:
  stage: build
  image: ghcr.io/nordsecurity/nordvpn-linux/depender:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
    - !reference [.cond/on-click, rules]
  script: $CI_PROJECT_DIR/ci/licenses.sh
  dependencies: []
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*
