# package.yml defines jobs for making various Linux packages.
#
# ARCH variable is required to determine which openvpn binary to package
include: /ci/jobs/.cond.yml
package/deb:
  stage: package
  image: ghcr.io/nordsecurity/nordvpn-linux/packager:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
  script: $CI_PROJECT_DIR/ci/nfpm/build_packages_resources.sh deb
  dependencies:
    - build/data
    - build/licenses
    - build/binaries
    - build/openvpn
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/app/deb/*.deb
      - $CI_PROJECT_DIR/dist/symbols/deb/*.debug
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
package/deb-candidate:
  stage: package
  image: ghcr.io/nordsecurity/nordvpn-linux/packager:1.0.0
  rules:
    - !reference [.cond/on-click, rules]
  script: $CI_PROJECT_DIR/ci/nfpm/build_packages_resources.sh deb
  dependencies:
    - build/data
    - build/licenses
    - build/binaries-candidate
    - build/openvpn
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/app/deb/*.deb
      - $CI_PROJECT_DIR/dist/symbols/deb/*.debug
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
package/rpm:
  stage: package
  image: ghcr.io/nordsecurity/nordvpn-linux/packager:1.0.0
  rules:
    - !reference [.cond/on-main, rules]
    - !reference [.cond/on-version-tag, rules]
    - !reference [.cond/on-merge-request, rules]
  script: $CI_PROJECT_DIR/ci/nfpm/build_packages_resources.sh rpm
  dependencies:
    - build/data
    - build/licenses
    - build/binaries
    - build/openvpn
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/app/rpm/*.rpm
      - $CI_PROJECT_DIR/dist/symbols/rpm/*.debug
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
package/rpm-candidate:
  stage: package
  image: ghcr.io/nordsecurity/nordvpn-linux/packager:1.0.0
  rules:
    - !reference [.cond/on-click, rules]
  script: $CI_PROJECT_DIR/ci/nfpm/build_packages_resources.sh rpm
  dependencies:
    - build/data
    - build/licenses
    - build/binaries-candidate
    - build/openvpn
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/app/rpm/*.rpm
      - $CI_PROJECT_DIR/dist/symbols/rpm/*.debug
  parallel:
    matrix:
      - ARCH: [i386, amd64, armel, armhf, aarch64]
