// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.6
// source: protobuf/meshnet/fsnotify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NewTransferNotification defines a notification structure about a new transfer
type NewTransferNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                   // Identifier of a device
	Os         string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                   // Operating system of a peer
	FileName   string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`       // Name of a file which is being sent. Empty if file_count > 1
	FileCount  int32  `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`   // Amount of files being sent
	TransferId string `protobuf:"bytes,5,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // Transfer ID
}

func (x *NewTransferNotification) Reset() {
	*x = NewTransferNotification{}
	mi := &file_protobuf_meshnet_fsnotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTransferNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTransferNotification) ProtoMessage() {}

func (x *NewTransferNotification) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_meshnet_fsnotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTransferNotification.ProtoReflect.Descriptor instead.
func (*NewTransferNotification) Descriptor() ([]byte, []int) {
	return file_protobuf_meshnet_fsnotify_proto_rawDescGZIP(), []int{0}
}

func (x *NewTransferNotification) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *NewTransferNotification) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NewTransferNotification) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *NewTransferNotification) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *NewTransferNotification) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// NotifyNewTransferResponse defines a response of new transfer notification
type NotifyNewTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*NotifyNewTransferResponse_Empty
	//	*NotifyNewTransferResponse_UpdatePeerErrorCode
	//	*NotifyNewTransferResponse_ServiceErrorCode
	//	*NotifyNewTransferResponse_MeshnetErrorCode
	Response isNotifyNewTransferResponse_Response `protobuf_oneof:"response"`
}

func (x *NotifyNewTransferResponse) Reset() {
	*x = NotifyNewTransferResponse{}
	mi := &file_protobuf_meshnet_fsnotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewTransferResponse) ProtoMessage() {}

func (x *NotifyNewTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_meshnet_fsnotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewTransferResponse.ProtoReflect.Descriptor instead.
func (*NotifyNewTransferResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_meshnet_fsnotify_proto_rawDescGZIP(), []int{1}
}

func (m *NotifyNewTransferResponse) GetResponse() isNotifyNewTransferResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *NotifyNewTransferResponse) GetEmpty() *Empty {
	if x, ok := x.GetResponse().(*NotifyNewTransferResponse_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *NotifyNewTransferResponse) GetUpdatePeerErrorCode() UpdatePeerErrorCode {
	if x, ok := x.GetResponse().(*NotifyNewTransferResponse_UpdatePeerErrorCode); ok {
		return x.UpdatePeerErrorCode
	}
	return UpdatePeerErrorCode_PEER_NOT_FOUND
}

func (x *NotifyNewTransferResponse) GetServiceErrorCode() ServiceErrorCode {
	if x, ok := x.GetResponse().(*NotifyNewTransferResponse_ServiceErrorCode); ok {
		return x.ServiceErrorCode
	}
	return ServiceErrorCode_NOT_LOGGED_IN
}

func (x *NotifyNewTransferResponse) GetMeshnetErrorCode() MeshnetErrorCode {
	if x, ok := x.GetResponse().(*NotifyNewTransferResponse_MeshnetErrorCode); ok {
		return x.MeshnetErrorCode
	}
	return MeshnetErrorCode_NOT_REGISTERED
}

type isNotifyNewTransferResponse_Response interface {
	isNotifyNewTransferResponse_Response()
}

type NotifyNewTransferResponse_Empty struct {
	Empty *Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type NotifyNewTransferResponse_UpdatePeerErrorCode struct {
	UpdatePeerErrorCode UpdatePeerErrorCode `protobuf:"varint,2,opt,name=update_peer_error_code,json=updatePeerErrorCode,proto3,enum=meshpb.UpdatePeerErrorCode,oneof"`
}

type NotifyNewTransferResponse_ServiceErrorCode struct {
	ServiceErrorCode ServiceErrorCode `protobuf:"varint,3,opt,name=service_error_code,json=serviceErrorCode,proto3,enum=meshpb.ServiceErrorCode,oneof"`
}

type NotifyNewTransferResponse_MeshnetErrorCode struct {
	MeshnetErrorCode MeshnetErrorCode `protobuf:"varint,4,opt,name=meshnet_error_code,json=meshnetErrorCode,proto3,enum=meshpb.MeshnetErrorCode,oneof"`
}

func (*NotifyNewTransferResponse_Empty) isNotifyNewTransferResponse_Response() {}

func (*NotifyNewTransferResponse_UpdatePeerErrorCode) isNotifyNewTransferResponse_Response() {}

func (*NotifyNewTransferResponse_ServiceErrorCode) isNotifyNewTransferResponse_Response() {}

func (*NotifyNewTransferResponse_MeshnetErrorCode) isNotifyNewTransferResponse_Response() {}

var File_protobuf_meshnet_fsnotify_proto protoreflect.FileDescriptor

var file_protobuf_meshnet_fsnotify_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x6e,
	0x65, 0x74, 0x2f, 0x66, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d,
	0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01,
	0x0a, 0x17, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb6, 0x02, 0x0a, 0x19, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x16, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x13, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x48, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x6d, 0x65, 0x73,
	0x68, 0x6e, 0x65, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x4d,
	0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x6d, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f,
	0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76,
	0x70, 0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_meshnet_fsnotify_proto_rawDescOnce sync.Once
	file_protobuf_meshnet_fsnotify_proto_rawDescData = file_protobuf_meshnet_fsnotify_proto_rawDesc
)

func file_protobuf_meshnet_fsnotify_proto_rawDescGZIP() []byte {
	file_protobuf_meshnet_fsnotify_proto_rawDescOnce.Do(func() {
		file_protobuf_meshnet_fsnotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_meshnet_fsnotify_proto_rawDescData)
	})
	return file_protobuf_meshnet_fsnotify_proto_rawDescData
}

var file_protobuf_meshnet_fsnotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_meshnet_fsnotify_proto_goTypes = []any{
	(*NewTransferNotification)(nil),   // 0: meshpb.NewTransferNotification
	(*NotifyNewTransferResponse)(nil), // 1: meshpb.NotifyNewTransferResponse
	(*Empty)(nil),                     // 2: meshpb.Empty
	(UpdatePeerErrorCode)(0),          // 3: meshpb.UpdatePeerErrorCode
	(ServiceErrorCode)(0),             // 4: meshpb.ServiceErrorCode
	(MeshnetErrorCode)(0),             // 5: meshpb.MeshnetErrorCode
}
var file_protobuf_meshnet_fsnotify_proto_depIdxs = []int32{
	2, // 0: meshpb.NotifyNewTransferResponse.empty:type_name -> meshpb.Empty
	3, // 1: meshpb.NotifyNewTransferResponse.update_peer_error_code:type_name -> meshpb.UpdatePeerErrorCode
	4, // 2: meshpb.NotifyNewTransferResponse.service_error_code:type_name -> meshpb.ServiceErrorCode
	5, // 3: meshpb.NotifyNewTransferResponse.meshnet_error_code:type_name -> meshpb.MeshnetErrorCode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_meshnet_fsnotify_proto_init() }
func file_protobuf_meshnet_fsnotify_proto_init() {
	if File_protobuf_meshnet_fsnotify_proto != nil {
		return
	}
	file_protobuf_meshnet_empty_proto_init()
	file_protobuf_meshnet_peer_proto_init()
	file_protobuf_meshnet_service_response_proto_init()
	file_protobuf_meshnet_fsnotify_proto_msgTypes[1].OneofWrappers = []any{
		(*NotifyNewTransferResponse_Empty)(nil),
		(*NotifyNewTransferResponse_UpdatePeerErrorCode)(nil),
		(*NotifyNewTransferResponse_ServiceErrorCode)(nil),
		(*NotifyNewTransferResponse_MeshnetErrorCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_meshnet_fsnotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_meshnet_fsnotify_proto_goTypes,
		DependencyIndexes: file_protobuf_meshnet_fsnotify_proto_depIdxs,
		MessageInfos:      file_protobuf_meshnet_fsnotify_proto_msgTypes,
	}.Build()
	File_protobuf_meshnet_fsnotify_proto = out.File
	file_protobuf_meshnet_fsnotify_proto_rawDesc = nil
	file_protobuf_meshnet_fsnotify_proto_goTypes = nil
	file_protobuf_meshnet_fsnotify_proto_depIdxs = nil
}
