#!/usr/bin/env bash

case "$1" in
    0)
        rm -f /usr/share/applications/nordvpn.desktop
        update-desktop-database 2> /dev/null
        rm -f /usr/share/zsh/functions/Completion/Unix/_nordvpn
        rm -f /usr/share/bash-completion/completions/nordvpn
        rm -f /usr/lib/systemd/system/nordvpnd.*
        rm -f /usr/lib/systemd/tmpfiles.d/nordvpn.conf
        rm -f /etc/init.d/nordvpn
        rm -rf /root/.{cache,config}/nordvpn
        rm -rf /usr/share/doc/nordvpn
        rm -rf /var/{lib,log}/nordvpn
        rm -rf /run/nordvpn
        rm -rf /etc/ld.so.conf.d/nordvpn.conf
        ldconfig
    ;;
esac

exit 0
