#!/usr/bin/env bash

DEFAULT_USER=${SUDO_USER:-"$(logname 2> /dev/null)"}
if [[ ! "$DEFAULT_USER" || "$DEFAULT_USER" == "root" ]]; then
    DEFAULT_USER=$(id -un -- "1000" 2> /dev/null)
fi
DEFAULT_USER_ID=$(id -u ${DEFAULT_USER})
ENV=$(ps --no-headers -o comm 1)

export XDG_RUNTIME_DIR="/run/user/${DEFAULT_USER_ID}"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

# NOTE: We found some really strange behavior with `ldconfig` cache refresh here.
# On .deb systems, using just `ldconfig` causes the nordvpnd daemon to fail on
# the first start with error that .so are missing. On restart, it's working again.
# Adding ANY flag to `ldconfig` (even the one we added on our own which does
# literally nothing) fixes the issue.
ldconfig

# move the symlink file creation later, otherwise the update scripts will delete it
ln -sf $(ldconfig -p | awk '/libsqlite3.so.0/ && /=>/ {print $NF; exit}') /usr/lib/nordvpn/libsqlite3.so

# ldconfig needs to be executed twice in case libsqlite3.so.0 was not available during a lookup
ldconfig


# cleanup files from older version 
if [[ -f "/etc/systemd/system/nordvpnd.service" ]]; then
    rm -f /etc/systemd/system/nordvpnd.service || true
fi
if [[ -f "/etc/systemd/system/nordvpnd.socket" ]]; then
    rm -f /etc/systemd/system/nordvpnd.socket || true
fi
if [[ -S "/run/nordvpnd.sock" ]]; then
    rm -f /run/nordvpnd.sock || true
fi

case "$ENV" in
    init)
        update-rc.d nordvpn defaults &>/dev/null || :
        /etc/init.d/nordvpn restart &>/dev/null || :
    ;;
    systemd)
        systemctl daemon-reload &>/dev/null || :
        systemd-tmpfiles --create || :
        systemctl enable nordvpnd.socket &>/dev/null || :
        systemctl enable nordvpnd.service &>/dev/null || :
        systemctl start nordvpnd.socket &>/dev/null || :
        systemctl start nordvpnd.service &>/dev/null || :
    ;;
    *)
        echo "Unknown init system, not running. Please start the daemon /usr/sbin/nordvpnd manually"
    ;;
esac

exit 0
