#!/usr/bin/env bash

LOG_DIR="/var/log/nordvpn"
DEFAULT_USER=${SUDO_USER:-"$(logname 2> /dev/null)"}
if [[ ! "$DEFAULT_USER" || "$DEFAULT_USER" == "root" ]]; then
    DEFAULT_USER=$(id -un -- "1000" 2> /dev/null)
fi
DEFAULT_USER_ID=$(id -u ${DEFAULT_USER})
ENV=$(ps --no-headers -o comm 1)
NORDVPN_GROUP="nordvpn"
ADD_USER_MESSAGE="Adding user '$DEFAULT_USER' to the group '$NORDVPN_GROUP'"

installSuccess="NordVPN for Linux successfully installed!"
userAddMessage=', please re-login or execute `su - $USER` in the current shell'
userShowMessage=""
if [[ "$DEFAULT_USER" ]]; then
    userShowMessage="$userAddMessage"
fi
quickTutorial="To get started${userShowMessage}, type 'nordvpn login' and enter your NordVPN account details."
quickTutorialConnect="Then type 'nordvpn connect' and you’re all set!"
groupMessage="All users belonging to the '$NORDVPN_GROUP' group will be allowed to control the NordVPN application."
groupAddedMessage="By default the user '$DEFAULT_USER' was added to the '$NORDVPN_GROUP' group during installation."
userModMessage="To allow other users to control the application run 'usermod -aG $NORDVPN_GROUP otheruser'."
userDelMessage="To limit access exclusively to the root user, remove all users from the '$NORDVPN_GROUP' group."
helpMessage="If you need help using the app, use the command 'nordvpn --help'."

# update configuration and shared library cache for linker to find .so files
echo "/usr/lib/nordvpn" > /etc/ld.so.conf.d/nordvpn.conf

# NOTE: We found some really strange behavior with `ldconfig` cache refresh here.
# On .deb systems, using just `ldconfig` causes the nordvpnd daemon to fail on
# the first start with error that .so are missing. On restart, it's working again.
# Adding ANY flag to `ldconfig` (even the one we added on our own which does
# literally nothing) fixes the issue.
ldconfig

ln -sf $(ldconfig -p | awk '/libsqlite3.so.0/ && /=>/ {print $NF; exit}') /usr/lib/nordvpn/libsqlite3.so

# ldconfig needs to be executed twice in case libsqlite3.so.0 was not available during a lookup
ldconfig

groupadd --system "$NORDVPN_GROUP" 1>/dev/null 2> /dev/null
groupCreated=$?

mkdir -m 0750 -p "$LOG_DIR"
chown root:$NORDVPN_GROUP "$LOG_DIR"

# TODO: Do we need this?
export XDG_RUNTIME_DIR="/run/user/${DEFAULT_USER_ID}"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

case "$1" in
    1)
        update-desktop-database 2> /dev/null
        gpasswd -M "" "$NORDVPN_GROUP"
        if [[ "$DEFAULT_USER" ]]; then
            usermod -aG "$NORDVPN_GROUP" "$DEFAULT_USER"
            echo "$ADD_USER_MESSAGE"
        fi
        case "$ENV" in
            init)
                update-rc.d nordvpn defaults &>/dev/null || :
                /etc/init.d/nordvpn restart &>/dev/null || :
            ;;
            systemd)
                systemctl daemon-reload &>/dev/null || :
                systemd-tmpfiles --create || :
                systemctl enable nordvpnd.socket &>/dev/null || :
                systemctl enable nordvpnd.service &>/dev/null || :
                systemctl start nordvpnd.socket &>/dev/null || :
                systemctl start nordvpnd.service &>/dev/null || :
            ;;
            *)
                mkdir -p /dev/net || :
                [[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200 || :
                [[ -e /usr/sbin/ip ]] || ln -s /sbin/ip /usr/sbin/ip || :
            ;;
        esac
        if [[ "$DEFAULT_USER" ]]; then
            su -c 'source /usr/share/bash-completion/completions/nordvpn' "${DEFAULT_USER}" &>/dev/null || :
        fi

        echo "$installSuccess"
        echo "$quickTutorial"
        echo "$quickTutorialConnect"
        echo "NOTE: $groupMessage"
        if [[ "$DEFAULT_USER" ]]; then
            echo "      $groupAddedMessage"
        fi
        echo "      $userModMessage"
        echo "      $userDelMessage"
        echo "$helpMessage"
    ;;
    2)
        # On upgrade add user only if group did not exist before
        if [[ "$groupCreated" -eq 0 ]]; then
            if [[ "$DEFAULT_USER" ]]; then
                usermod -aG "$NORDVPN_GROUP" "$DEFAULT_USER"
                echo "$ADD_USER_MESSAGE"
            fi
        fi
    ;;
esac

exit 0
