#!/usr/bin/env bash

if [ -x "/snap/bin/nordvpn" ]; then
    echo ""
    echo "====================================================================================="
    echo "NordVPN is already installed via Snap."
    echo "To install the app from a RPM package, first remove the Snap version."
    echo "====================================================================================="
    echo ""
    exit 1
fi

exit 0
