#!/usr/bin/env bash

if [ -x "/snap/bin/nordvpn" ]; then
    echo ""
    echo "====================================================================================="
    echo "NordVPN application Snap package is already installed!"
    echo "If you want to install NordVPN from rpm package - remove NordVPN snap package first."
    echo "====================================================================================="
    echo ""
    exit 1
fi

exit 0
