#!/usr/bin/env bash

ENV=$(ps --no-headers -o comm 1)

case "$1" in
    0)
        case "$ENV" in
            init)
                /etc/init.d/nordvpn stop &>/dev/null || :
                update-rc.d -f nordvpn remove &>/dev/null || :
            ;;
            systemd)
                systemctl stop nordvpnd.service &>/dev/null || :
                systemctl stop nordvpnd.socket &>/dev/null || :
                systemctl disable nordvpnd.service &>/dev/null || :
                systemctl disable nordvpnd.socket &>/dev/null || :
                systemctl daemon-reload &>/dev/null || :
            ;;
            *sh) # executed in docker
            ;;
            *)
                echo "[ERROR] Unknown environment \`$ENV'"
            ;;
        esac
    ;;
    1)
        case "$ENV" in
        init)
            /etc/init.d/nordvpn upgrade-stop &>/dev/null || :
            update-rc.d -f nordvpn remove &>/dev/null || :
        ;;
        systemd)
            sudo systemctl set-property nordvpnd.service Restart=no &>/dev/null || :
            sudo systemctl kill --signal=SIGUSR1 nordvpnd.service &>/dev/null || :
            sudo systemctl stop nordvpnd.socket &>/dev/null || :
            sudo systemctl disable nordvpnd.service &>/dev/null || :
            sudo systemctl disable nordvpnd.socket &>/dev/null || :
            sudo systemctl daemon-reload &>/dev/null || :
        ;;
        *sh) # executed in docker
        ;;
        *)
            echo "[ERROR] Unknown environment \`$ENV'"
        ;;
        esac
    ;;
esac

exit 0
