# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - snapcraft-bin:/usr/local/bin
    command: sleep infinity
    privileged: true
    networks:
      - devcontainer-network
    depends_on:
      - snaper

  snaper:
    image: ghcr.io/nordsecurity/nordvpn-linux/snaper:1.2.0
    volumes:
      - snapcraft-bin:/shared
    command: sh -c "cp /usr/bin/snapcraft /shared/ && sleep infinity"
    networks:
      - devcontainer-network

volumes:
  snapcraft-bin:

networks:
  devcontainer-network:
    driver: bridge