// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.6
// source: protobuf/daemon/config/vpn_protocol.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VPNProtocol int32

const (
	VPNProtocol_VPN_PROTOCOL_UNSPECIFIED VPNProtocol = 0
	VPNProtocol_VPN_PROTOCOL_NORDLYNX    VPNProtocol = 1
	VPNProtocol_VPN_PROTOCOL_OPENVPN_UDP VPNProtocol = 2
	VPNProtocol_VPN_PROTOCOL_OPENVPN_TCP VPNProtocol = 3
	VPNProtocol_VPN_PROTOCOL_NORDWHISPER VPNProtocol = 4
)

// Enum value maps for VPNProtocol.
var (
	VPNProtocol_name = map[int32]string{
		0: "VPN_PROTOCOL_UNSPECIFIED",
		1: "VPN_PROTOCOL_NORDLYNX",
		2: "VPN_PROTOCOL_OPENVPN_UDP",
		3: "VPN_PROTOCOL_OPENVPN_TCP",
		4: "VPN_PROTOCOL_NORDWHISPER",
	}
	VPNProtocol_value = map[string]int32{
		"VPN_PROTOCOL_UNSPECIFIED": 0,
		"VPN_PROTOCOL_NORDLYNX":    1,
		"VPN_PROTOCOL_OPENVPN_UDP": 2,
		"VPN_PROTOCOL_OPENVPN_TCP": 3,
		"VPN_PROTOCOL_NORDWHISPER": 4,
	}
)

func (x VPNProtocol) Enum() *VPNProtocol {
	p := new(VPNProtocol)
	*p = x
	return p
}

func (x VPNProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VPNProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_daemon_config_vpn_protocol_proto_enumTypes[0].Descriptor()
}

func (VPNProtocol) Type() protoreflect.EnumType {
	return &file_protobuf_daemon_config_vpn_protocol_proto_enumTypes[0]
}

func (x VPNProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VPNProtocol.Descriptor instead.
func (VPNProtocol) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_daemon_config_vpn_protocol_proto_rawDescGZIP(), []int{0}
}

var File_protobuf_daemon_config_vpn_protocol_proto protoreflect.FileDescriptor

var file_protobuf_daemon_config_vpn_protocol_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x70, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2a, 0xa0, 0x01, 0x0a, 0x0b, 0x56, 0x50, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x18, 0x56, 0x50, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x56, 0x50, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x4e, 0x4f, 0x52, 0x44, 0x4c, 0x59, 0x4e, 0x58, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18,
	0x56, 0x50, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x4f, 0x50, 0x45,
	0x4e, 0x56, 0x50, 0x4e, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x56, 0x50,
	0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x56,
	0x50, 0x4e, 0x5f, 0x54, 0x43, 0x50, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x56, 0x50, 0x4e, 0x5f,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x4e, 0x4f, 0x52, 0x44, 0x57, 0x48, 0x49,
	0x53, 0x50, 0x45, 0x52, 0x10, 0x04, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76, 0x70, 0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_daemon_config_vpn_protocol_proto_rawDescOnce sync.Once
	file_protobuf_daemon_config_vpn_protocol_proto_rawDescData = file_protobuf_daemon_config_vpn_protocol_proto_rawDesc
)

func file_protobuf_daemon_config_vpn_protocol_proto_rawDescGZIP() []byte {
	file_protobuf_daemon_config_vpn_protocol_proto_rawDescOnce.Do(func() {
		file_protobuf_daemon_config_vpn_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_daemon_config_vpn_protocol_proto_rawDescData)
	})
	return file_protobuf_daemon_config_vpn_protocol_proto_rawDescData
}

var file_protobuf_daemon_config_vpn_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_daemon_config_vpn_protocol_proto_goTypes = []any{
	(VPNProtocol)(0), // 0: config.VPNProtocol
}
var file_protobuf_daemon_config_vpn_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_daemon_config_vpn_protocol_proto_init() }
func file_protobuf_daemon_config_vpn_protocol_proto_init() {
	if File_protobuf_daemon_config_vpn_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_daemon_config_vpn_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_daemon_config_vpn_protocol_proto_goTypes,
		DependencyIndexes: file_protobuf_daemon_config_vpn_protocol_proto_depIdxs,
		EnumInfos:         file_protobuf_daemon_config_vpn_protocol_proto_enumTypes,
	}.Build()
	File_protobuf_daemon_config_vpn_protocol_proto = out.File
	file_protobuf_daemon_config_vpn_protocol_proto_rawDesc = nil
	file_protobuf_daemon_config_vpn_protocol_proto_goTypes = nil
	file_protobuf_daemon_config_vpn_protocol_proto_depIdxs = nil
}
