// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.6
// source: protobuf/daemon/login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginType int32

const (
	LoginType_LoginType_UNKNOWN LoginType = 0
	LoginType_LoginType_LOGIN   LoginType = 1
	LoginType_LoginType_SIGNUP  LoginType = 2
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LoginType_UNKNOWN",
		1: "LoginType_LOGIN",
		2: "LoginType_SIGNUP",
	}
	LoginType_value = map[string]int32{
		"LoginType_UNKNOWN": 0,
		"LoginType_LOGIN":   1,
		"LoginType_SIGNUP":  2,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_daemon_login_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_protobuf_daemon_login_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{0}
}

type LoginOAuth2Status int32

const (
	LoginOAuth2Status_SUCCESS              LoginOAuth2Status = 0
	LoginOAuth2Status_UNKNOWN_OAUTH2_ERROR LoginOAuth2Status = 1
	LoginOAuth2Status_ALREADY_LOGGED_IN    LoginOAuth2Status = 2
	LoginOAuth2Status_NO_NET               LoginOAuth2Status = 3
)

// Enum value maps for LoginOAuth2Status.
var (
	LoginOAuth2Status_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_OAUTH2_ERROR",
		2: "ALREADY_LOGGED_IN",
		3: "NO_NET",
	}
	LoginOAuth2Status_value = map[string]int32{
		"SUCCESS":              0,
		"UNKNOWN_OAUTH2_ERROR": 1,
		"ALREADY_LOGGED_IN":    2,
		"NO_NET":               3,
	}
)

func (x LoginOAuth2Status) Enum() *LoginOAuth2Status {
	p := new(LoginOAuth2Status)
	*p = x
	return p
}

func (x LoginOAuth2Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginOAuth2Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_daemon_login_proto_enumTypes[1].Descriptor()
}

func (LoginOAuth2Status) Type() protoreflect.EnumType {
	return &file_protobuf_daemon_login_proto_enumTypes[1]
}

func (x LoginOAuth2Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginOAuth2Status.Descriptor instead.
func (LoginOAuth2Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{1}
}

type LoginOAuth2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type LoginType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.LoginType" json:"type,omitempty"`
}

func (x *LoginOAuth2Request) Reset() {
	*x = LoginOAuth2Request{}
	mi := &file_protobuf_daemon_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOAuth2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOAuth2Request) ProtoMessage() {}

func (x *LoginOAuth2Request) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_daemon_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOAuth2Request.ProtoReflect.Descriptor instead.
func (*LoginOAuth2Request) Descriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginOAuth2Request) GetType() LoginType {
	if x != nil {
		return x.Type
	}
	return LoginType_LoginType_UNKNOWN
}

type LoginOAuth2CallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type  LoginType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.LoginType" json:"type,omitempty"`
}

func (x *LoginOAuth2CallbackRequest) Reset() {
	*x = LoginOAuth2CallbackRequest{}
	mi := &file_protobuf_daemon_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOAuth2CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOAuth2CallbackRequest) ProtoMessage() {}

func (x *LoginOAuth2CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_daemon_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOAuth2CallbackRequest.ProtoReflect.Descriptor instead.
func (*LoginOAuth2CallbackRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginOAuth2CallbackRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginOAuth2CallbackRequest) GetType() LoginType {
	if x != nil {
		return x.Type
	}
	return LoginType_LoginType_UNKNOWN
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int64  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Url  string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_protobuf_daemon_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_daemon_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LoginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LoginOAuth2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status LoginOAuth2Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.LoginOAuth2Status" json:"status,omitempty"`
	Url    string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *LoginOAuth2Response) Reset() {
	*x = LoginOAuth2Response{}
	mi := &file_protobuf_daemon_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOAuth2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOAuth2Response) ProtoMessage() {}

func (x *LoginOAuth2Response) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_daemon_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOAuth2Response.ProtoReflect.Descriptor instead.
func (*LoginOAuth2Response) Descriptor() ([]byte, []int) {
	return file_protobuf_daemon_login_proto_rawDescGZIP(), []int{3}
}

func (x *LoginOAuth2Response) GetStatus() LoginOAuth2Status {
	if x != nil {
		return x.Status
	}
	return LoginOAuth2Status_SUCCESS
}

func (x *LoginOAuth2Response) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_protobuf_daemon_login_proto protoreflect.FileDescriptor

var file_protobuf_daemon_login_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x37, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x55, 0x0a, 0x1a, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x35, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x56, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x2a, 0x4d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x55, 0x50, 0x10, 0x02, 0x2a,
	0x5d, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4f, 0x41, 0x55,
	0x54, 0x48, 0x32, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41,
	0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x4c, 0x4f, 0x47, 0x47, 0x45, 0x44, 0x5f, 0x49, 0x4e,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x5f, 0x4e, 0x45, 0x54, 0x10, 0x03, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x72,
	0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76, 0x70,
	0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_daemon_login_proto_rawDescOnce sync.Once
	file_protobuf_daemon_login_proto_rawDescData = file_protobuf_daemon_login_proto_rawDesc
)

func file_protobuf_daemon_login_proto_rawDescGZIP() []byte {
	file_protobuf_daemon_login_proto_rawDescOnce.Do(func() {
		file_protobuf_daemon_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_daemon_login_proto_rawDescData)
	})
	return file_protobuf_daemon_login_proto_rawDescData
}

var file_protobuf_daemon_login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_daemon_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_daemon_login_proto_goTypes = []any{
	(LoginType)(0),                     // 0: pb.LoginType
	(LoginOAuth2Status)(0),             // 1: pb.LoginOAuth2Status
	(*LoginOAuth2Request)(nil),         // 2: pb.LoginOAuth2Request
	(*LoginOAuth2CallbackRequest)(nil), // 3: pb.LoginOAuth2CallbackRequest
	(*LoginResponse)(nil),              // 4: pb.LoginResponse
	(*LoginOAuth2Response)(nil),        // 5: pb.LoginOAuth2Response
}
var file_protobuf_daemon_login_proto_depIdxs = []int32{
	0, // 0: pb.LoginOAuth2Request.type:type_name -> pb.LoginType
	0, // 1: pb.LoginOAuth2CallbackRequest.type:type_name -> pb.LoginType
	1, // 2: pb.LoginOAuth2Response.status:type_name -> pb.LoginOAuth2Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_daemon_login_proto_init() }
func file_protobuf_daemon_login_proto_init() {
	if File_protobuf_daemon_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_daemon_login_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_daemon_login_proto_goTypes,
		DependencyIndexes: file_protobuf_daemon_login_proto_depIdxs,
		EnumInfos:         file_protobuf_daemon_login_proto_enumTypes,
		MessageInfos:      file_protobuf_daemon_login_proto_msgTypes,
	}.Build()
	File_protobuf_daemon_login_proto = out.File
	file_protobuf_daemon_login_proto_rawDesc = nil
	file_protobuf_daemon_login_proto_goTypes = nil
	file_protobuf_daemon_login_proto_depIdxs = nil
}
