// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.6
// source: recent_connections.proto

package pb

import (
	config "github.com/NordSecurity/nordvpn-linux/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecentConnectionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of recent connections information
	Connections []*RecentConnectionModel `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
}

func (x *RecentConnectionsResponse) Reset() {
	*x = RecentConnectionsResponse{}
	mi := &file_recent_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentConnectionsResponse) ProtoMessage() {}

func (x *RecentConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recent_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentConnectionsResponse.ProtoReflect.Descriptor instead.
func (*RecentConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_recent_connections_proto_rawDescGZIP(), []int{0}
}

func (x *RecentConnectionsResponse) GetConnections() []*RecentConnectionModel {
	if x != nil {
		return x.Connections
	}
	return nil
}

type RecentConnectionModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Country name
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	// City name
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// Group name
	Group config.ServerGroup `protobuf:"varint,3,opt,name=group,proto3,enum=config.ServerGroup" json:"group,omitempty"`
	// Country code (2 characters)
	CountryCode string `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Human-readable server name
	SpecificServerName string `protobuf:"bytes,5,opt,name=specific_server_name,json=specificServerName,proto3" json:"specific_server_name,omitempty"`
	// Specific server identifier
	SpecificServer string `protobuf:"bytes,6,opt,name=specific_server,json=specificServer,proto3" json:"specific_server,omitempty"`
	// Connection type enum
	ConnectionType config.ServerSelectionRule `protobuf:"varint,7,opt,name=connection_type,json=connectionType,proto3,enum=pb.ServerSelectionRule" json:"connection_type,omitempty"`
}

func (x *RecentConnectionModel) Reset() {
	*x = RecentConnectionModel{}
	mi := &file_recent_connections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentConnectionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentConnectionModel) ProtoMessage() {}

func (x *RecentConnectionModel) ProtoReflect() protoreflect.Message {
	mi := &file_recent_connections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentConnectionModel.ProtoReflect.Descriptor instead.
func (*RecentConnectionModel) Descriptor() ([]byte, []int) {
	return file_recent_connections_proto_rawDescGZIP(), []int{1}
}

func (x *RecentConnectionModel) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RecentConnectionModel) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RecentConnectionModel) GetGroup() config.ServerGroup {
	if x != nil {
		return x.Group
	}
	return config.ServerGroup(0)
}

func (x *RecentConnectionModel) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *RecentConnectionModel) GetSpecificServerName() string {
	if x != nil {
		return x.SpecificServerName
	}
	return ""
}

func (x *RecentConnectionModel) GetSpecificServer() string {
	if x != nil {
		return x.SpecificServer
	}
	return ""
}

func (x *RecentConnectionModel) GetConnectionType() config.ServerSelectionRule {
	if x != nil {
		return x.ConnectionType
	}
	return config.ServerSelectionRule(0)
}

type RecentConnectionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Limit maximum entries to be returned, 0 - no limit
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RecentConnectionsRequest) Reset() {
	*x = RecentConnectionsRequest{}
	mi := &file_recent_connections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentConnectionsRequest) ProtoMessage() {}

func (x *RecentConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recent_connections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentConnectionsRequest.ProtoReflect.Descriptor instead.
func (*RecentConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_recent_connections_proto_rawDescGZIP(), []int{2}
}

func (x *RecentConnectionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_recent_connections_proto protoreflect.FileDescriptor

var file_recent_connections_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x58, 0x0a, 0x19, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xb0, 0x02, 0x0a, 0x15, 0x52, 0x65,
	0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x29, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x30, 0x0a, 0x14, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x18,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x72,
	0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76, 0x70,
	0x6e, 0x2d, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recent_connections_proto_rawDescOnce sync.Once
	file_recent_connections_proto_rawDescData = file_recent_connections_proto_rawDesc
)

func file_recent_connections_proto_rawDescGZIP() []byte {
	file_recent_connections_proto_rawDescOnce.Do(func() {
		file_recent_connections_proto_rawDescData = protoimpl.X.CompressGZIP(file_recent_connections_proto_rawDescData)
	})
	return file_recent_connections_proto_rawDescData
}

var file_recent_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recent_connections_proto_goTypes = []any{
	(*RecentConnectionsResponse)(nil), // 0: pb.RecentConnectionsResponse
	(*RecentConnectionModel)(nil),     // 1: pb.RecentConnectionModel
	(*RecentConnectionsRequest)(nil),  // 2: pb.RecentConnectionsRequest
	(config.ServerGroup)(0),           // 3: config.ServerGroup
	(config.ServerSelectionRule)(0),   // 4: pb.ServerSelectionRule
}
var file_recent_connections_proto_depIdxs = []int32{
	1, // 0: pb.RecentConnectionsResponse.connections:type_name -> pb.RecentConnectionModel
	3, // 1: pb.RecentConnectionModel.group:type_name -> config.ServerGroup
	4, // 2: pb.RecentConnectionModel.connection_type:type_name -> pb.ServerSelectionRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recent_connections_proto_init() }
func file_recent_connections_proto_init() {
	if File_recent_connections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recent_connections_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recent_connections_proto_goTypes,
		DependencyIndexes: file_recent_connections_proto_depIdxs,
		MessageInfos:      file_recent_connections_proto_msgTypes,
	}.Build()
	File_recent_connections_proto = out.File
	file_recent_connections_proto_rawDesc = nil
	file_recent_connections_proto_goTypes = nil
	file_recent_connections_proto_depIdxs = nil
}
