// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.6
// source: uievent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UIFormReference identifies the UI form or screen from which an action
// originated
type UIEvent_FormReference int32

const (
	UIEvent_FORM_REFERENCE_UNSPECIFIED UIEvent_FormReference = 0
	UIEvent_CLI                        UIEvent_FormReference = 1
	UIEvent_TRAY                       UIEvent_FormReference = 2
	UIEvent_HOME_SCREEN                UIEvent_FormReference = 3
)

// Enum value maps for UIEvent_FormReference.
var (
	UIEvent_FormReference_name = map[int32]string{
		0: "FORM_REFERENCE_UNSPECIFIED",
		1: "CLI",
		2: "TRAY",
		3: "HOME_SCREEN",
	}
	UIEvent_FormReference_value = map[string]int32{
		"FORM_REFERENCE_UNSPECIFIED": 0,
		"CLI":                        1,
		"TRAY":                       2,
		"HOME_SCREEN":                3,
	}
)

func (x UIEvent_FormReference) Enum() *UIEvent_FormReference {
	p := new(UIEvent_FormReference)
	*p = x
	return p
}

func (x UIEvent_FormReference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIEvent_FormReference) Descriptor() protoreflect.EnumDescriptor {
	return file_uievent_proto_enumTypes[0].Descriptor()
}

func (UIEvent_FormReference) Type() protoreflect.EnumType {
	return &file_uievent_proto_enumTypes[0]
}

func (x UIEvent_FormReference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIEvent_FormReference.Descriptor instead.
func (UIEvent_FormReference) EnumDescriptor() ([]byte, []int) {
	return file_uievent_proto_rawDescGZIP(), []int{0, 0}
}

// ItemName represents a user interface event item name
type UIEvent_ItemName int32

const (
	UIEvent_ITEM_NAME_UNSPECIFIED UIEvent_ItemName = 0
	UIEvent_CONNECT               UIEvent_ItemName = 1
	UIEvent_CONNECT_RECENTS       UIEvent_ItemName = 2
	UIEvent_DISCONNECT            UIEvent_ItemName = 3
	UIEvent_LOGIN                 UIEvent_ItemName = 4
	UIEvent_LOGOUT                UIEvent_ItemName = 5
	UIEvent_RATE_CONNECTION       UIEvent_ItemName = 6
	UIEvent_MESHNET_INVITE_SEND   UIEvent_ItemName = 7
)

// Enum value maps for UIEvent_ItemName.
var (
	UIEvent_ItemName_name = map[int32]string{
		0: "ITEM_NAME_UNSPECIFIED",
		1: "CONNECT",
		2: "CONNECT_RECENTS",
		3: "DISCONNECT",
		4: "LOGIN",
		5: "LOGOUT",
		6: "RATE_CONNECTION",
		7: "MESHNET_INVITE_SEND",
	}
	UIEvent_ItemName_value = map[string]int32{
		"ITEM_NAME_UNSPECIFIED": 0,
		"CONNECT":               1,
		"CONNECT_RECENTS":       2,
		"DISCONNECT":            3,
		"LOGIN":                 4,
		"LOGOUT":                5,
		"RATE_CONNECTION":       6,
		"MESHNET_INVITE_SEND":   7,
	}
)

func (x UIEvent_ItemName) Enum() *UIEvent_ItemName {
	p := new(UIEvent_ItemName)
	*p = x
	return p
}

func (x UIEvent_ItemName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIEvent_ItemName) Descriptor() protoreflect.EnumDescriptor {
	return file_uievent_proto_enumTypes[1].Descriptor()
}

func (UIEvent_ItemName) Type() protoreflect.EnumType {
	return &file_uievent_proto_enumTypes[1]
}

func (x UIEvent_ItemName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIEvent_ItemName.Descriptor instead.
func (UIEvent_ItemName) EnumDescriptor() ([]byte, []int) {
	return file_uievent_proto_rawDescGZIP(), []int{0, 1}
}

// ItemType represents the type of user interface event
type UIEvent_ItemType int32

const (
	UIEvent_ITEM_TYPE_UNSPECIFIED UIEvent_ItemType = 0
	UIEvent_CLICK                 UIEvent_ItemType = 1
)

// Enum value maps for UIEvent_ItemType.
var (
	UIEvent_ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "CLICK",
	}
	UIEvent_ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED": 0,
		"CLICK":                 1,
	}
)

func (x UIEvent_ItemType) Enum() *UIEvent_ItemType {
	p := new(UIEvent_ItemType)
	*p = x
	return p
}

func (x UIEvent_ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIEvent_ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_uievent_proto_enumTypes[2].Descriptor()
}

func (UIEvent_ItemType) Type() protoreflect.EnumType {
	return &file_uievent_proto_enumTypes[2]
}

func (x UIEvent_ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIEvent_ItemType.Descriptor instead.
func (UIEvent_ItemType) EnumDescriptor() ([]byte, []int) {
	return file_uievent_proto_rawDescGZIP(), []int{0, 2}
}

// ItemValue represents the value associated with a user interface event
type UIEvent_ItemValue int32

const (
	UIEvent_ITEM_VALUE_UNSPECIFIED UIEvent_ItemValue = 0
	UIEvent_COUNTRY                UIEvent_ItemValue = 1
	UIEvent_CITY                   UIEvent_ItemValue = 2
	UIEvent_DIP                    UIEvent_ItemValue = 3
	UIEvent_MESHNET                UIEvent_ItemValue = 4
	UIEvent_OBFUSCATED             UIEvent_ItemValue = 5
	UIEvent_ONION_OVER_VPN         UIEvent_ItemValue = 6
	UIEvent_DOUBLE_VPN             UIEvent_ItemValue = 7
	UIEvent_P2P                    UIEvent_ItemValue = 8
)

// Enum value maps for UIEvent_ItemValue.
var (
	UIEvent_ItemValue_name = map[int32]string{
		0: "ITEM_VALUE_UNSPECIFIED",
		1: "COUNTRY",
		2: "CITY",
		3: "DIP",
		4: "MESHNET",
		5: "OBFUSCATED",
		6: "ONION_OVER_VPN",
		7: "DOUBLE_VPN",
		8: "P2P",
	}
	UIEvent_ItemValue_value = map[string]int32{
		"ITEM_VALUE_UNSPECIFIED": 0,
		"COUNTRY":                1,
		"CITY":                   2,
		"DIP":                    3,
		"MESHNET":                4,
		"OBFUSCATED":             5,
		"ONION_OVER_VPN":         6,
		"DOUBLE_VPN":             7,
		"P2P":                    8,
	}
)

func (x UIEvent_ItemValue) Enum() *UIEvent_ItemValue {
	p := new(UIEvent_ItemValue)
	*p = x
	return p
}

func (x UIEvent_ItemValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIEvent_ItemValue) Descriptor() protoreflect.EnumDescriptor {
	return file_uievent_proto_enumTypes[3].Descriptor()
}

func (UIEvent_ItemValue) Type() protoreflect.EnumType {
	return &file_uievent_proto_enumTypes[3]
}

func (x UIEvent_ItemValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIEvent_ItemValue.Descriptor instead.
func (UIEvent_ItemValue) EnumDescriptor() ([]byte, []int) {
	return file_uievent_proto_rawDescGZIP(), []int{0, 3}
}

// UIEvent contains nested enums for UI event tracking
type UIEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UIEvent) Reset() {
	*x = UIEvent{}
	mi := &file_uievent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEvent) ProtoMessage() {}

func (x *UIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_uievent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEvent.ProtoReflect.Descriptor instead.
func (*UIEvent) Descriptor() ([]byte, []int) {
	return file_uievent_proto_rawDescGZIP(), []int{0}
}

var File_uievent_proto protoreflect.FileDescriptor

var file_uievent_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xc3, 0x03, 0x0a, 0x07, 0x55, 0x49, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x53, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e,
	0x43, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x43, 0x4c, 0x49, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x52, 0x41,
	0x59, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x4f, 0x4d, 0x45, 0x5f, 0x53, 0x43, 0x52, 0x45,
	0x45, 0x4e, 0x10, 0x03, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e,
	0x4e, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x4e, 0x54, 0x53, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x47,
	0x4f, 0x55, 0x54, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f,
	0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45,
	0x53, 0x48, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x4e,
	0x44, 0x10, 0x07, 0x22, 0x30, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c,
	0x49, 0x43, 0x4b, 0x10, 0x01, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x56, 0x41, 0x4c, 0x55,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x43, 0x49, 0x54, 0x59, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x50, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x48, 0x4e, 0x45, 0x54, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x42, 0x46, 0x55, 0x53, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e,
	0x4f, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x5f, 0x56, 0x50, 0x4e, 0x10, 0x06,
	0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x5f, 0x56, 0x50, 0x4e, 0x10, 0x07,
	0x12, 0x07, 0x0a, 0x03, 0x50, 0x32, 0x50, 0x10, 0x08, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x76, 0x70, 0x6e, 0x2d, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uievent_proto_rawDescOnce sync.Once
	file_uievent_proto_rawDescData = file_uievent_proto_rawDesc
)

func file_uievent_proto_rawDescGZIP() []byte {
	file_uievent_proto_rawDescOnce.Do(func() {
		file_uievent_proto_rawDescData = protoimpl.X.CompressGZIP(file_uievent_proto_rawDescData)
	})
	return file_uievent_proto_rawDescData
}

var file_uievent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_uievent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uievent_proto_goTypes = []any{
	(UIEvent_FormReference)(0), // 0: pb.UIEvent.FormReference
	(UIEvent_ItemName)(0),      // 1: pb.UIEvent.ItemName
	(UIEvent_ItemType)(0),      // 2: pb.UIEvent.ItemType
	(UIEvent_ItemValue)(0),     // 3: pb.UIEvent.ItemValue
	(*UIEvent)(nil),            // 4: pb.UIEvent
}
var file_uievent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uievent_proto_init() }
func file_uievent_proto_init() {
	if File_uievent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uievent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uievent_proto_goTypes,
		DependencyIndexes: file_uievent_proto_depIdxs,
		EnumInfos:         file_uievent_proto_enumTypes,
		MessageInfos:      file_uievent_proto_msgTypes,
	}.Build()
	File_uievent_proto = out.File
	file_uievent_proto_rawDesc = nil
	file_uievent_proto_goTypes = nil
	file_uievent_proto_depIdxs = nil
}
