name: nordvpn-gui
title: NordVPN GUI
version: 0.0.1
summary: NordVPN GUI application
description: NordVPN GUI application

confinement: strict
base: core22
grade: stable

icon: snap/gui/nordvpn-gui.svg
website: https://nordvpn.com
license: GPL-3.0
contact: support@nordvpn.com
source-code: https://github.com/NordSecurity/nordvpn-linux-gui

apps:
  nordvpn-gui:
    command: nordvpn-gui
    extensions: [gnome]
    plugs:
      - nordvpn-socket

parts:
  nordvpn-gui:
    source: .
    plugin: flutter

plugs:
  nordvpn-socket:
    interface: system-files
    read:
      - /run/nordvpn/nordvpnd.sock
    write:
      - /run/nordvpn/nordvpnd.sock