d /run/nordvpn 0770 root nordvpn
# NOTE:
# For install scripts, /var dirs are read-only during installation on immutable
# distributions (like Fedora Silverblue), so after installation those
# directories do not have enough permissions for moose to access the database.
# To fix this, we are instructing systemd here to apply correct
# permissions.
d /var/lib/nordvpn      0750 root nordvpn
d /var/lib/nordvpn/data 0750 root nordvpn
