#!/usr/bin/env bash

case "$1" in
    purge|remove)
    ${UNINSTALL_SCRIPT}
    
    ;;
    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;
    *)
        echo "$0: didn't understand being called with \`$1'" 1>&2
        exit 0
    ;;
esac

exit 0
