#!/usr/bin/env bash

case "$1" in
install | abort-upgrade)
    # Nothing to do yet
    ;;
upgrade)
    # Stopping the old process
    pkill -TERM -x nordvpn-gui || :
    ;;
*)
    echo "preinst called with unknown argument '$1'" >&2
    # deliberately no error returned
    ;;
esac

exit 0
