name: nordvpn
base: core22
summary: TODO
description: |
  TODO
adopt-info: nordvpn
confinement: strict

apps:
  nordvpn:
    command: bin/nordvpn
    environment:
      PREFIX_COMMON: $SNAP_COMMON
      PREFIX_DATA: $SNAP_DATA
      PREFIX_STATIC: $SNAP
      USER_DATA: $SNAP_USER_COMMON
    plugs:
      - home
      - network
      - network-bind
    completer: usr/share/bash-completion/completions/nordvpn
    # Snap does not support zsh autocompletions. In order to enable them, after installing snap,
    # execute:
    #
    # sudo ln -s /snap/nordvpn/current/usr/share/zsh/functions/Completion/Unix/_nordvpn_auto_complete /usr/share/zsh/functions/Completion/Unix/_nordvpn_auto_complete
    # compinit
    #
    desktop: usr/share/applications/nordvpn.desktop
  nordvpnd:
    command: bin/nordvpnd
    daemon: simple
    environment:
      PREFIX_COMMON: $SNAP_COMMON
      PREFIX_DATA: $SNAP_DATA
      PREFIX_STATIC: $SNAP
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
parts:
  nordvpn:
    plugin: nil
    source-type: local
    source: .
    override-build: |
      # When it is executed in git submodule and contents of `.` are copied to
      # `./parts/nordvpn/build`, .git file points to the invalid host repository
      sed -i 's/\.\./..\/..\/..\/../g' .git || true
      WORKDIR=$(pwd) source ./ci/env.sh
      sed -i 's\VERSION\'"${VERSION}"'\g' contrib/snap/appdata.xml
      cp contrib/snap/appdata.xml ${SNAPCRAFT_PART_INSTALL}/com.nordsec.nordvpn.appdata.xml
    parse-info: [com.nordsec.nordvpn.appdata.xml]

  nordvpn-bin:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/i386
      - on amd64: ./bin/amd64
      - on armel: ./bin/armel
      - on armhf: ./bin/armhf
      - on aarch64: ./bin/aarch64
    stage-packages:
      - wireguard-tools
      - libxml2
      - e2fsprogs
    organize:
      nordvpn: bin/nordvpn
      nordvpnd: bin/nordvpnd
    stage:
      - bin/*
      - usr/*

  nordfileshare:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/i386
      - on amd64: ./bin/amd64
      - on armel: ./bin/armel
      - on armhf: ./bin/armhf
      - on aarch64: ./bin/aarch64
    organize:
      nordfileshare: var/lib/nordvpn/nordfileshare
    stage:
      - var/lib/nordvpn/nordfileshare

  openvpn-bin:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/deps/openvpn/i386/latest/
      - on amd64: ./bin/deps/openvpn/amd64/latest/
      - on armel: ./bin/deps/openvpn/armel/latest/
      - on armhf: ./bin/deps/openvpn/armhf/latest/
      - on aarch64: ./bin/deps/openvpn/aarch64/latest/
    organize:
      openvpn: var/lib/nordvpn/openvpn
    stage:
      - var/lib/nordvpn/openvpn

  autocomplete:
    plugin: dump
    source-type: local
    source: dist/autocomplete
    organize:
      bash_autocomplete: usr/share/bash-completion/completions/nordvpn
      zsh_autocomplete: usr/share/zsh/functions/Completion/Unix/_nordvpn_auto_complete

  data:
    plugin: dump
    source-type: local
    source: dist/data
    organize:
      countries.dat: var/lib/nordvpn/data/countries.dat
      ovpn_template.xslt: var/lib/nordvpn/data/ovpn_template.xslt
      ovpn_xor_template.xslt: var/lib/nordvpn/data/ovpn_xor_template.xslt
      servers.dat: var/lib/nordvpn/data/servers.dat

  desktop:
    plugin: dump
    source-type: local
    source: contrib/desktop
    override-build: |
      sed -i 's\Icon=nordvpn\Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/nordvpn.svg\g' nordvpn.desktop
      cp nordvpn.desktop ${SNAPCRAFT_PART_INSTALL}/nordvpn.desktop
    organize:
      nordvpn.desktop: usr/share/applications/nordvpn.desktop

  assets:
    plugin: dump
    source-type: local
    source: assets
    organize:
      icon.svg: usr/share/icons/hicolor/scalable/apps/nordvpn.svg

  # Contents of this part are not affecting the functionality in any way but they are here for
  # convenience
  dist:
    plugin: dump
    source-type: local
    source: dist
    organize:
      THIRD-PARTY-NOTICES.md: usr/share/licenses/nordvpn/THIRD-PARTY-NOTICES.md
        # Snap does not support manpages. In order to enable them, after installing snap, execute:
        #
        # sudo ln -s /snap/nordvpn/current/usr/share/man/man1/nordvpn.1.gz /usr/share/man/man1/nordvpn.1.gz
        #
      nordvpn.1.gz: usr/share/man/man1/nordvpn.1.gz
      changelog.yml: usr/share/doc/nordvpn/changelog.yml
