name: nordvpn
base: core22
version: '3.17.0'
summary: TODO
description: |
  TODO

grade: devel
confinement: strict

apps:
  nordvpn:
    command: bin/nordvpn
    environment:
      PREFIX_COMMON: $SNAP_COMMON
      PREFIX_DATA: $SNAP_DATA
      PREFIX_STATIC: $SNAP
      USER_DATA: $SNAP_USER_COMMON
    plugs:
      - home
      - network
      - network-bind
  nordvpnd:
    command: bin/nordvpnd
    daemon: simple
    environment:
      PREFIX_COMMON: $SNAP_COMMON
      PREFIX_DATA: $SNAP_DATA
      PREFIX_STATIC: $SNAP
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
parts:
  nordvpn-bin:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/i386
      - on amd64: ./bin/amd64
      - on armel: ./bin/armel
      - on armhf: ./bin/armhf
      - on aarch64: ./bin/aarch64
    stage-packages:
      - wireguard-tools
      - libxml2
      - e2fsprogs
    organize:
      nordvpn: bin/nordvpn
      nordvpnd: bin/nordvpnd
    stage:
      - bin/*
      - usr/*

  nordfileshare:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/i386
      - on amd64: ./bin/amd64
      - on armel: ./bin/armel
      - on armhf: ./bin/armhf
      - on aarch64: ./bin/aarch64
    organize:
      nordfileshare: var/lib/nordvpn/nordfileshare
    stage:
      - var/lib/nordvpn/nordfileshare

  openvpn-bin:
    plugin: dump
    source-type: local
    source:
      - on i386: ./bin/deps/openvpn/i386/latest/
      - on amd64: ./bin/deps/openvpn/amd64/latest/
      - on armel: ./bin/deps/openvpn/armel/latest/
      - on armhf: ./bin/deps/openvpn/armhf/latest/
      - on aarch64: ./bin/deps/openvpn/aarch64/latest/
    organize:
      openvpn: var/lib/nordvpn/openvpn
    stage:
      - var/lib/nordvpn/openvpn
