#!/usr/bin/env bash

case "$1" in
    purge)
        usrInfo=$(awk -F: '{if ($3 >= 1000 && $3 <= 2000) print $6}' < /etc/passwd)
        IFS=$'\n'
        for usrLine in $usrInfo; do
            # for each user remove user settings and logs dirs
            rm -rf $usrLine/.{cache,config}/nordvpn
        done
    ;&  # fallthrough
    remove)
        rm -f /usr/share/applications/nordvpn.desktop
        update-desktop-database 2> /dev/null
        rm -f /usr/share/zsh/functions/Completion/Unix/_nordvpn
        rm -f /usr/share/bash-completion/completions/nordvpn
        rm -f /usr/lib/systemd/system/nordvpnd.*
        rm -f /usr/lib/systemd/tmpfiles.d/nordvpn.conf
        rm -f /etc/init.d/nordvpn
        rm -rf /root/.{cache,config}/nordvpn
        rm -rf /usr/share/doc/nordvpn
        rm -rf /var/{lib,log}/nordvpn
        rm -rf /run/nordvpn
        rm -rf /etc/ld.so.conf.d/nordvpn.conf
        rm -rf /usr/lib/nordvpn/libsqlite3.so

        # NOTE: We found some really strange behavior with `ldconfig` cache refresh here.
        # On .deb systems, using just `ldconfig` causes the nordvpnd daemon to fail on
        # the first start with error that .so are missing. On restart, it's working again.
        # Adding ANY flag to `ldconfig` (even the one we added on our own which does
        # literally nothing) fixes the issue.
        ldconfig -v > /dev/null 2>&1
    ;;
    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;
    *)
        echo "$0: didn't understand being called with \`$1'" 1>&2
        exit 0
    ;;
esac

exit 0
