#!/usr/bin/env bash

LOG_DIR="/var/log/nordvpn"
DEFAULT_USER=${SUDO_USER:-"$(logname 2> /dev/null)"}
if [[ ! "$DEFAULT_USER" || "$DEFAULT_USER" == "root" ]]; then
    DEFAULT_USER=$(id -un -- "1000" 2> /dev/null)
fi
DEFAULT_USER_ID=$(id -u ${DEFAULT_USER})
ENV=$(ps --no-headers -o comm 1)
NORDVPN_GROUP="nordvpn"
ADD_USER_MESSAGE="Adding user '$DEFAULT_USER' to the group '$NORDVPN_GROUP'"

installSuccess="NordVPN for Linux successfully installed!"
userAddMessage=', please re-login or execute `su - $USER` in the current shell'
userShowMessage=""
if [[ "$DEFAULT_USER" ]]; then
    userShowMessage="$userAddMessage"
fi
quickTutorial="To get started${userShowMessage}, type 'nordvpn login' and enter your NordVPN account details."
quickTutorialConnect="Then type 'nordvpn connect' and you’re all set!"
groupMessage="All users belonging to the '$NORDVPN_GROUP' group will be allowed to control the NordVPN application."
groupAddedMessage="By default the user '$DEFAULT_USER' was added to the '$NORDVPN_GROUP' group during installation."
userModMessage="To allow other users to control the application run 'usermod -aG $NORDVPN_GROUP otheruser'."
userDelMessage="To limit access exclusively to the root user, remove all users from the '$NORDVPN_GROUP' group."
helpMessage="If you need help using the app, use the command 'nordvpn --help'."

ldconfig # update shared library cache
mkdir -m 0750 -p "$LOG_DIR"
chown root:$NORDVPN_GROUP "$LOG_DIR"

# TODO: Do we need this?
export XDG_RUNTIME_DIR="/run/user/${DEFAULT_USER_ID}"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

case "$1" in
    configure)
        update-desktop-database 2> /dev/null
        mkdir -m 0750 -p "$LOG_DIR"
        chown root:$NORDVPN_GROUP "$LOG_DIR"

        # Cleanup files from older version without systemd
        if [[ -f "/etc/systemd/system/nordvpnd.service" ]]; then
            rm -f /etc/systemd/system/nordvpnd.service || true
        fi
        if [[ -f "/etc/systemd/system/nordvpnd.socket" ]]; then
            rm -f /etc/systemd/system/nordvpnd.socket || true
        fi
        if [[ -S "/run/nordvpnd.sock" ]]; then
            rm -f /run/nordvpnd.sock || true
        fi
        case "$ENV" in
            init)
                update-rc.d nordvpn defaults &>/dev/null || :
                /etc/init.d/nordvpn restart &>/dev/null || :
            ;;
            systemd)
                systemctl daemon-reload &>/dev/null || :
                systemd-tmpfiles --create || :
                systemctl enable nordvpnd.socket &>/dev/null || :
                systemctl enable nordvpnd.service &>/dev/null || :
                systemctl start nordvpnd.socket &>/dev/null || :
                systemctl start nordvpnd.service &>/dev/null || :
            ;;
            *)
                mkdir -p /dev/net || :
                [[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200 || :
                [[ -e /usr/sbin/ip ]] || ln -s /sbin/ip /usr/sbin/ip || :
            ;;
        esac

        if [[ "$DEFAULT_USER" ]]; then
            su -c 'source /usr/share/bash-completion/completions/nordvpn' "${DEFAULT_USER}" &>/dev/null || true
        fi

        # Message will be shown only on fresh install (after purge)
        if [[ ! "$2" ]]; then
            echo "$installSuccess"
            echo "$quickTutorial"
            echo "$quickTutorialConnect"
            echo "NOTE: $groupMessage"
            if [[ "$DEFAULT_USER" ]]; then
                echo "      $groupAddedMessage"
            fi
            echo "      $userModMessage"
            echo "      $userDelMessage"
            echo "$helpMessage"
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "[ERROR] postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
