name: GUI tests
on: [workflow_call]

permissions:
  packages: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/nordsecurity/nordvpn-linux/flutter-3.32.8:1.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get dependencies
        working-directory: ./gui
        run: |
          flutter pub get

      - name: Start Xvfb manually
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /tmp/xvfb.log 2>&1 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run unit-tests
        working-directory: ./gui
        run: |
          flutter test --fail-fast -d linux --verbose

      - name: Run integration tests
        working-directory: ./gui
        run: |
          flutter test --fail-fast integration_test/e2e_tests/app_test.dart -d linux --verbose

      - name: Run smoke tests
        working-directory: ./gui
        run: |
          flutter test --fail-fast integration_test/smoke_tests/smoke_tests.dart -d linux --verbose
