name: Trigger GitLab pipeline
on:
  pull_request_target:
    types: [labeled]
  push:
    branches-ignore: 
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions: {}
jobs:
  trigger-gitlab-pipeline:
    uses: NordSecurity/trigger-gitlab-pipeline/.github/workflows/trigger-gitlab-pipeline.yml@LLT-5701_implement_reusable_workflow_to_enable_workflow_pinning_on_non_ephemeral_runners # TODO specify git hash once it gets merged
    secrets:
      ci-api-v4-url: ${{ secrets.CI_API_V4_URL }}
      access-token: ${{ secrets.GITLAB_API_TOKEN }}
      trigger-token: ${{ secrets.TOKEN }}
      project-id: ${{ secrets.PROJECT_ID }}
    with:
      schedule: ${{ github.event_name == 'schedule' }}
      cancel-outdated-pipelines: ${{ github.ref_name != 'main' }}
      triggered-ref: v2.4.9 # REMEMBER to also update in .gitlab-ci.yml
