# This workflow decides what part of the automation should run
# based on the changed files:
# - GUI only changes - run automation only for GUI
# - core (everything except GUI changes) - run automation for both CLI and GUI
name: CI orchestrator

on:
  push:
    branches: [LVPN-8657_test_run] # XXX: change this
  # pull_request:
  # push:
  #   tags: ["[0-9]+.[0-9]+.[0-9]+"]

permissions: {}

jobs:
  changes: # based on changed file paths, decide if we can run GUI only or all automation
    runs-on: ubuntu-22.04
    outputs:
      core: ${{ steps.filter.outputs.core }}
      gui: ${{ steps.filter.outputs.gui }}
      matrix_json: ${{ steps.choose.outputs.matrix_json }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with: { fetch-depth: 0 }

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          predicate-quantifier: "every"
          filters: |
            core:
              - '**'        # everything...
              - '!gui/**'   # ...except GUI
            gui:
              - 'gui/**'

      - name: Decide which suites to run
        id: choose
        run: |
          if [ "${{ steps.filter.outputs.core }}" = "true" ]; then
            echo 'matrix_json=["core","gui"]' >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.filter.outputs.gui }}" = "true" ]; then
            echo 'matrix_json=["gui"]' >> "$GITHUB_OUTPUT"
          else
            echo 'matrix_json=[]' >> "$GITHUB_OUTPUT"
          fi

  suite: # run separate `_suite` for EACH entry in `matrix`
    needs: changes
    if: ${{ fromJSON(needs.changes.outputs.matrix_json).length > 0 }}
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.changes.outputs.matrix_json) }}
    uses: ./.github/workflows/_suite.yml
    with:
      suite: ${{ matrix.suite }}
