name: CI orchestrator

on:
  pull_request:
  push:
    branches: ["**"]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-orchestrator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  decide:
    name: Detect GUI-only vs core change
    runs-on: ubuntu-22.04
    outputs:
      gui_changed: ${{ steps.decide.outputs.gui_changed }}
      core_changed: ${{ steps.decide.outputs.core_changed }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Decide
        id: decide
        run: python3 ci/detect_changes.py --gui-dir gui

  # Run core CI when any non-GUI file changed
  core_ci:
    needs: decide
    if: needs.decide.outputs.core_changed == 'true'
    uses: ./.github/workflows/_core_ci.yml

  # Run GUI CI when GUI changed (GUI-only or along with core)
  gui_ci:
    needs: decide
    if: needs.decide.outputs.core_changed == 'true' || needs.decide.outputs.gui_changed == 'true'
    uses: ./.github/workflows/_gui_ci.yml
