# By default this workflow will be running for PRs (rapid scans) and on push to main branch (full scan)
on:
  pull_request_target:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  
jobs:
  sca:
    uses: NordSecurity/security-scanner-workflows/.github/workflows/sca.yml@35c715910e21a4b84949be8c8be3432f5c2911ce
    secrets:
      SCA_URL: ${{ secrets.SCA_URL }}
      SCA_API_TOKEN: ${{ secrets.SCA_API_TOKEN }}
      SCA_ACTION_KEY: ${{ secrets.SCA_ACTION_KEY }}
      UNC_ACTION_KEY: ${{ secrets.UNC_ACTION_KEY }}
    with:
      project-action-path: nordsecurity-nordvpn-linux-sca-action