#!/bin/sh
echo "==============================                       calling the hook"
echo "==============================                       calling the hook" >/tmp/calllog
if [ "$(cat ${SNAP_COMMON}/connections/hardware-observe 2>/dev/null)" -ne "1" ]; then
  snapctl restart nordvpn.nordvpnd
fi
