#!/bin/sh

INTERFACE_NAME="network-control"

if snapctl is-connected ${INTERFACE_NAME}; then
  echo "The ${INTERFACE_NAME} interface is connected. Restarting the Snap container..."
  snapctl restart nordvpn.nordvpnd
else
  echo "The ${INTERFACE_NAME} interface is not connected."
fi
